libseccomp: bump to version 2.1.1
Version 1.0.0 was not compatible with systemd. With 1.0.0, systemd
compilation produce:

src/shared/seccomp-util.c: In function 'seccomp_add_secondary_archs':
src/shared/seccomp-util.c:73:9: warning: implicit declaration of function 'seccomp_arch_add' [-Wimplicit-function-declaration]
         r = seccomp_arch_add(c, SCMP_ARCH_X86);
         ^
src/shared/seccomp-util.c:73:9: warning: nested extern declaration of 'seccomp_arch_add' [-Wnested-externs]
src/shared/seccomp-util.c:73:33: error: 'SCMP_ARCH_X86' undeclared (first use in this function)
         r = seccomp_arch_add(c, SCMP_ARCH_X86);
                                 ^
src/shared/seccomp-util.c:77:33: error: 'SCMP_ARCH_X86_64' undeclared (first use in this function)
         r = seccomp_arch_add(c, SCMP_ARCH_X86_64);
                                 ^
src/shared/seccomp-util.c:81:33: error: 'SCMP_ARCH_X32' undeclared (first use in this function)
         r = seccomp_arch_add(c, SCMP_ARCH_X32);

Signed-off-by: Jérôme Pouiller <jezz@sysmic.org>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>