macchanger: add patch to fix musl build
Add a patch to fix a build error with the musl C library.

caddr_t is defined in <sys/types.h>. This header file must be included to fix
build with the musl C library:

netinfo.c: In function 'mc_net_info_get_permanent_mac':
netinfo.c:116:28: error: 'caddr_t' undeclared (first use in this function)
  req.ifr_data = (caddr_t)epa;

The project looks dead, the last commit dates Jan 1, 2014. So the fix is not
sent upstream.

Fixes:
http://autobuild.buildroot.net/results/796/7966ad4f994d893918368891107f660295164f07/
http://autobuild.buildroot.net/results/177/177db3c7cbb59e4388c6742e987f92df53a23fc3/
.. and many more

Replaces:
http://patchwork.ozlabs.org/patch/572195/

Signed-off-by: Jörg Krause <joerg.krause@embedded.rocks>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>