package/libsvgtiny: disable parallel build
Build can sometimes fails on:

src/svgtiny.c:21:10: fatal error: autogenerated_colors.c: No such file or directory
 #include "autogenerated_colors.c"
          ^~~~~~~~~~~~~~~~~~~~~~~~

because svgtiny.c does not properly depends on autogenerated_colors.c
that is built by gperf. So, just disable parallel build instead of
trying to fix this issue especially because libsvgtiny uses the netsurf
buildsystem

Fixes:
 - http://autobuild.buildroot.org/results/48e7a7f7c72634d59cca817778d31661bfe8e72f

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>