Revert "package/python-sip: bump to version 4.19.13"
This reverts commit 9135ab7a7c76b38b50dadbc381c55e77c86e9e0d. This
version bump causes a major issue: the entire root filesystem of the
build machine is being copied into $(STAGING_DIR)/usr/lib/python2.7/,
causing the build to consume the entire disk space of the machine.

>>> python-sip 4.19.13 Installing to target
[...]
make[2]: Leaving directory `/home/test/buildroot/output/build/python-sip-4.19.13/siplib'
Traceback (most recent call last):
  File "/home/test/buildroot/output/build/python-sip-4.19.13/mk_distinfo.py", line 108, in <module>
    fn_f = open(fn, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/home/test/buildroot/output/target/usr/lib/python3.7/site-packages/sip.pyi'
make[1]: *** [install_distinfo] Error 1
make[1]: *** Waiting for unfinished jobs....
cp: cannot open `/proc/fs/aufs/plink_maint' for reading: Permission denied
cp: cannot open `/proc/sys/fs/protected_fifos' for reading: Permission denied
cp: cannot open `/proc/sys/fs/protected_hardlinks' for reading: Permission denied
cp: cannot open `/proc/sys/fs/protected_regular' for reading: Permission denied
cp: cannot open `/proc/sys/fs/protected_symlinks' for reading: Permission denied
cp: cannot open `/proc/sys/kernel/cad_pid' for reading: Permission denied
cp: cannot open `/proc/sys/kernel/unprivileged_userns_apparmor_policy' for reading: Permission denied
cp: cannot open `/proc/sys/kernel/usermodehelper/bset' for reading: Permission denied
...

Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>