net-tools: fix field with incomplete type error
Update 0002 patch to match the one sent as a pull request. The previous
one introduced a new problem that has been addressed in the new version.

Some Linux headers included in certain toolchains may not have an
updated linux/if_tunnel.h which includes linux/ip.h, so we need to
include it unconditionally otherwise linux/if_tunnel.h will use the
struct iphdr before being defined and the compilation will fail in this
way:

In file included from iptunnel.c:33:0:
/usr/include/linux/if_tunnel.h:37:16: error: field 'iph' has incomplete
type
  struct iphdr  iph;
                  ^

Pull request URL:
  https://sourceforge.net/p/net-tools/code/merge-requests/4/

Fixes:
  http://autobuild.buildroot.net/results/34f/34f9b10ef6a613057e8f6457d8a0a2fa142ad123/

Signed-off-by: Vicente Olivert Riera <Vincent.Riera@imgtec.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>