configs/zynq_microzed: uboot: bump to xilinx-v2018.2 (fixes build)
Bump to the most recent Xilinx release.

Fixes:
  .../output/host/include/libfdt_env.h:71:30: error: conflicting types for ‘fdt64_t’
  .../output/host/include/libfdt_env.h:91:24: error: expected ‘)’ before ‘x’
  .../output/host/include/libfdt.h:150:21: error: redefinition of ‘fdt_offset_ptr_w’
...and many, many other similar errors.

[Build-tested only]
Tested-by: Luca Ceresoli <luca@lucaceresoli.net>
Signed-off-by: Luca Ceresoli <luca@lucaceresoli.net>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>