package/openzwave: fix strncat build failure
Retrieve upstream patch that fixes a build failure caused by
strncat():

error: 'char* strncat(char*, const char*, size_t)' output may be truncated copying between 0 and 253 bytes from a string of length 253

This patch also allow to disable the use of the bundled tinyxml
library so use this new option and add a dependency of openzwave on
tinyxml to use it as a regular external library.

Fixes:

  http://autobuild.buildroot.org/results/cbe0671831d874a5b96a944b891fe1eea823667b

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>