dhcpcd: needs MMU
dhcpcd fails to build on non-MMU platforms, even with the
--disable-fork option:

  bind.o: In function `_daemonise':
  bind.c:(.text+0x62): undefined reference to `_fork'
  collect2: ld returned 1 exit status

Therefore, we make dhcpcd depend on MMU support, and remove the
non-MMU condition in the .mk file. More recent versions of dhcpcd do
support non-MMU properly, but this commit intends to be only a fix.

Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>
Acked-by: "Yann E. MORIN" <yann.morin.1998@free.fr>
Acked-by: Samuel Martin <s.martin49@gmail.com>