bcache-tools: fix build with gcc-5
Backport a Debian patch to fix a build failure with gcc-5:

bcache.c:125:9: warning: 'crc_table' is static but used in inline
function 'crc64' which is not static
...
make-bcache.c:277: undefined reference to `crc64'

This issue has been reported upstream but is not yet fixed.

Fixes:

  http://autobuild.buildroot.net/results/410/410954d33206475d70b8e5ba55a2c955a229af9b/

Signed-off-by: Vicente Olivert Riera <Vincent.Riera@imgtec.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>