filemq: disable documentation generation
The parameter to disable asciidoc documentation generation changed from
'fmq_have_asciidoc' to 'filemq_have_asciidoc'.

Fixes [1], [2], [3]:

  File "/usr/bin/asciidoc", line 101
    except KeyError, k: raise AttributeError, k
                   ^
  SyntaxError: invalid syntax

[1] http://autobuild.buildroot.net/results/5f0/5f0558235756419eff15b8e909b5d630712f5141
[2] http://autobuild.buildroot.net/results/a23/a23d92b09dadc12b3753c951900e28fc19bd14cd
[3] http://autobuild.buildroot.net/results/a45/a450ff5c6008ccf290a028e6eab7ff26369243e7

Signed-off-by: Peter Seiderer <ps.report@gmx.net>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>