package/x11r7/xdriver_xf86-video-ati: Depends on xlib_libXcomposite
When xserver_xorg-server is built without composite support building this
package will fail:

radeon_dri2.c: In function 'radeon_dri2_copy_region2':
radeon_dri2.c:438:28: error: 'struct _Pixmap' has no member named 'screen_x'
  off_x = drawable->x - pPix->screen_x;
                            ^
radeon_dri2.c:439:28: error: 'struct _Pixmap' has no member named 'screen_y'
  off_y = drawable->y - pPix->screen_y;

Signed-off-by: Bernd Kuhls <bernd.kuhls@t-online.de>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>