configs/rock64: Linux needs host OpenSSL
The Linux configuration used in the rock64_defconfig requires
host-openssl to be built, otherwise the build fails with:

scripts/extract-cert.c:21:25: fatal error: openssl/bio.h: No such file or directory
 #include <openssl/bio.h>

So let's enable BR2_LINUX_KERNEL_NEEDS_HOST_OPENSSL.

Fixes:

  https://gitlab.com/buildroot.org/buildroot/-/jobs/165766161

Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>