package/glorytun: bump to version 2.0.1
mud/aegis256/aegis256.c:6:18: error: missing binary operator before token "("
 #if __has_include("x86intrin.h")
                  ^

is fixed through
https://github.com/angt/aegis256/commit/4ff57bfc839b696cbc34651586d232ec8e1db275

Fixes:
 - http://autobuild.buildroot.org/results/f03b0ec68e14e4562df13ce484da34115b113c02

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>