qt5base: fix eglfs compile for odroid-mali
Avoid duplicated struct fbdev_window definition (introduced by [1]) by
renaming struct fbdev_window to shadow_fbdev_window.

Fixes [2]:

qeglfsmaliintegration.cpp:45:8: error: redefinition of 'struct fbdev_window'
 struct fbdev_window {
        ^
In file included from /accts/mlweber1/rc-buildroot-test/scripts/instance-0/output/host/usr/aarch64-buildroot-linux-gnu/sysroot/usr/include/EGL/eglplatform.h:28:0,
                 from /accts/mlweber1/rc-buildroot-test/scripts/instance-0/output/host/usr/aarch64-buildroot-linux-gnu/sysroot/usr/include/EGL/egl.h:36,
                 from ../../../eglfs/qeglfsglobal.h:45,
                 from ../../../eglfs/qeglfsdeviceintegration.h:48,
                 from qeglfsmaliintegration.h:37,
                 from qeglfsmaliintegration.cpp:34:

[1] https://code.qt.io/cgit/qt/qtbase.git/commit/?h=dev&id=58bed4cda98e8e25db8adc61c7db73b6853077dc
[2] http://autobuild.buildroot.net/results/48c/48c458c035162169e8ca7c34ae65e9064822f25a

Signed-off-by: Peter Seiderer <ps.report@gmx.net>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>