xapp_xkbevd: depends on MMU
Fixes http://sysmic.org/~jezz/results/a9ec03bd:

xkbevd.o: In function `_main':
xkbevd.c:(.text+0x3ca): undefined reference to `_fork'
collect2: ld returned 1 exit status

Signed-off-by: Jérôme Pouiller <jezz@sysmic.org>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>