package/wayland: requires shared library
Fixes
  CC       src/libwayland_server_la-wayland-server.lo
src/wayland-server.c:36:19: error: dlfcn.h: No such file or directory

using this defconfig
http://autobuild.buildroot.net/results/dfd/dfd81f1f1f0f315317b2a85d24b286a277ac7c16/

Signed-off-by: Bernd Kuhls <bernd.kuhls@t-online.de>
Reviewed-by: "Yann E. MORIN" <yann.morin.1998@free.fr>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>