package/pwgen: bump to version 2.08
Also add hash for license file

Fixes:

$: make pwgen-legal-info
>>> pwgen 2.08 Collecting legal info
 ERROR: No hash found for debian/copyright

Signed-off-by: Pierre-Jean Texier <pjtexier@koncepto.io>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>