package/iwd: bump version to 1.5
Fixes incompatibility because of recent version bump to ell-0.28 ([1]):

  http://autobuild.buildroot.net/results/32899d7e1f7d5abc528e5627f8f66ae5c9733342
  http://autobuild.buildroot.net/results/a0a4387e5319d792658f6d82a63fb17a06848d10
  http://autobuild.buildroot.net/results/7d02c966518e44d798b83ac36b9083a8041b09ec
  http://autobuild.buildroot.net/results/f7b27ab243e6b35445d9cb28e4747514fa7d98d6
  http://autobuild.buildroot.net/results/f5d71af640812a58374374e178cb7ff225e69c19

    CC       src/main.o
  src/main.c: In function 'request_name_callback':
  src/main.c:167:7: error: too few arguments to function 'l_dbus_object_manager_enable'
    if (!l_dbus_object_manager_enable(dbus))
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
  In file included from /nvmedata/autobuild/instance-4/output-1/host/powerpc-buildroot-linux-uclibc/sysroot/usr/include/ell/ell.h:55,
                   from src/main.c:32:
  /nvmedata/autobuild/instance-4/output-1/host/powerpc-buildroot-linux-uclibc/sysroot/usr/include/ell/dbus.h:245:6: note: declared here
   bool l_dbus_object_manager_enable(struct l_dbus *dbus, const char *root);
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~

[1] https://git.buildroot.net/buildroot/commit/?id=faa592179d9fe46b97289bde5a1b0f0da6052b06

Signed-off-by: Peter Seiderer <ps.report@gmx.net>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>