binutils: more fixes for arc-2015.06 tools
Two patches below are taken from development branch of ARC binutils,
so one the next release of ARC tools happens both patches must be removed.

These 2 patches:
 0003-ld-arc-Provide-the-.tdata-symbol.patch
 0004-Provide-.tbss-symbol.patch
fix missing .tbss and .tdata sections during linkage stage such as:
------------------------------>8---------------------------
arc-linux-g++ test.cpp
../arc-buildroot-linux-uclibc/lib/libstdc++.so: undefined reference to '.tbss'
collect2: error: ld returned 1 exit status
------------------------------>8---------------------------

Signed-off-by: Alexey Brodkin <abrodkin@synopsys.com>
Cc: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>