package/iqvlinux: new package
The PCI support needs to be checked since this driver is based
on it. Otherwise the build fail with:
 #error "This driver requires PCI support to be available"

But this message is concealed by several occurrence of this
one:
 error: implicit declaration of function 'pci_find_bus' [-Werror=implicit-function-declaration]

[Thomas:
 - fix minor typo in Config.in: s/Enthernet/Ethernet/
 - license is "GPLv2, BSD-3c", not "GPLv2 or BSD-3c"
 - remove IQVLINUX_PCI_CHECK, until a proper generic solution is
   implemented.]

Signed-off-by: Romain Naour <romain.naour@openwide.fr>
Cc: Yann E. MORIN <yann.morin.1998@free.fr>
Cc: Arnout Vandecappelle <arnout@mind.be>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>