acl: backport upstream patch to fix static build
When building tar package with acl in static build configuration, we
get definition clash error for 'quote' function.

../gnu/libgnu.a(quotearg.o): In function 'quote':
quotearg.c:(.text+0x12fc): multiple definition of 'quote'
../sysroot/usr/lib/libacl.a(quote.o):/home/test/autobuild/run/instance-1/output/build/acl-2.2.52/libmisc/quote.c:27: first defined here

In acl upstream, this is already fixed by renaming quote and unquote
internal functions. This commit backports upstream patch.

Fixes:
  http://autobuild.buildroot.net/results/d64/d64d13745c980d322d3b80c3b324d03eb7f17262

Signed-off-by: Rahul Bedarkar <rahul.bedarkar@imgtec.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>