package/berkeleydb: fix build error with gcc8
Fixes

../src/dbinc/atomic.h:179:19: error: definition of 'int __atomic_compare_exchange(db_atomic_t*,
 atomic_value_t, atomic_value_t)' ambiguates built-in declaration 'bool
 __atomic_compare_exchange(unsigned int, volatile void*, void*, void*, int, int)'
 static inline int __atomic_compare_exchange(
                   ^~~~~~~~~~~~~~~~~~~~~~~~~

To reproduce the build error use this defconfig

BR2_GCC_VERSION_8_X=y
BR2_TOOLCHAIN_BUILDROOT_CXX=y
BR2_PACKAGE_BERKELEYDB=y
BR2_PACKAGE_BERKELEYDB_COMPAT185=y
BR2_PACKAGE_BERKELEYDB_TOOLS=y

Please note that to trigger the error BR2_TOOLCHAIN_BUILDROOT_CXX=y
is needed although berkeleydb does not depend on c++.

Signed-off-by: Bernd Kuhls <bernd.kuhls@t-online.de>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>